version: '3.9'

services:
  api:
    image: emperorkautilya/news-vibes
    environment:
      DB_HOST: mysql_db:3306
      DB_NAME: news_db
      DB_USER: root
      DB_PASSWORD: password
    ports:
      - "5000:5000"
    depends_on:
      mysql_db:
        condition: service_healthy

  mysql_db:
    image: mysql
    environment:
      MYSQL_DATABASE: news_db
      MYSQL_ROOT_PASSWORD: password
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
