version: '3.9'

services:
  api:
    image: emperorkautilya/news-vibes
    environment:
      DB_HOST: mysql_news_database:3307
      DB_NAME: news_db
      DB_USER: root
      DB_PASSWORD: password
    ports:
      - "5000:5000"
    depends_on:
      mysql_news_database:
        condition: service_healthy

  mysql_news_database:
    image: mysql
    environment:
      MYSQL_DATABASE: news_db
      MYSQL_ROOT_PASSWORD: password
      MYSQL_TCP_PORT: 3307
    ports:
      - 3307:3307
    expose:
      - 3307
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
